### ISSUE TITLE
你的源码没有pakage.json无法npm install

### ISSUE THREAD

**Issue by cs-xiyan** [lizhihang1995/HIT-CS-Reexam#3]

**Comment by lizhihang1995** [comment]
抱歉，因为找不到 `package.json` 了，所以现在去掉了 gitbook 形式，可以直接看单个文档。

**Comment by lizhihang1995** [comment]
抱歉，因为找不到 package.json 了，所以现在去掉了 gitbook 形式，可以直接看单个文档。

**Comment by lizhihang1995** [comment]
抱歉，因为找不到 package.json 了，所以现在去掉了 gitbook 形式，可以直接看单个文档。

**Comment by lizhihang1995** [comment]
抱歉，因为找不到 package.json 了，所以现在去掉了 gitbook 形式，可以直接看单个文档。
